[package]
name = "telemetry-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.8"
axum-tracing-opentelemetry = { version = "0.9.0", features = ["otlp", "zipkin"] }
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
tracing-opentelemetry = "0.18"
opentelemetry-http = "0.7.0"
opentelemetry-zipkin = "0.16"
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "env-filter",
  "fmt",
  "json",
] }

[profile.dev]
lto = false
# https://jakedeichert.com/blog/reducing-rust-incremental-compilation-times-on-macos-by-70-percent/
split-debuginfo = "unpacked"
# Use slightly better optimizations
opt-level = 0
# Disable integer overflow checks
overflow-checks = false

[profile.release]
opt-level = 'z'
incremental = true
lto = true
# The Rust compiler splits your crate into multiple codegen units to parallelize (and thus speed up) compilation. However, this might cause it to miss some potential optimizations.
codegen-units = 1
