/// AWS DynamoDB fluent builder instrumentation implementations
/// Generated by GitHub Copilot with human guidance
use std::collections::HashSet;

use super::{AwsInstrumentBuilder, utils::*};
use crate::{middleware::aws::*, semconv};

impl<'a> AwsInstrumentBuilder<'a> for GetItemFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        let attributes = [
            self.get_consistent_read()
                .as_attribute(semconv::AWS_DYNAMODB_CONSISTENT_READ),
            self.get_projection_expression()
                .as_attribute(semconv::AWS_DYNAMODB_PROJECTION),
        ];
        DynamodbSpanBuilder::get_item(table_name)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::get_item);

impl<'a> AwsInstrumentBuilder<'a> for GetResourcePolicyFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_resource_arn().clone().unwrap_or_default();
        DynamodbSpanBuilder::get_resource_policy(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::get_resource_policy);

impl<'a> AwsInstrumentBuilder<'a> for PutItemFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::put_item(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::put_item);

impl<'a> AwsInstrumentBuilder<'a> for PutResourcePolicyFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_resource_arn().clone().unwrap_or_default();
        DynamodbSpanBuilder::put_resource_policy(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::put_resource_policy);

impl<'a> AwsInstrumentBuilder<'a> for UpdateItemFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::update_item(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::update_item);

impl<'a> AwsInstrumentBuilder<'a> for DeleteItemFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::delete_item(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::delete_item);

impl<'a> AwsInstrumentBuilder<'a> for DeleteResourcePolicyFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_resource_arn().clone().unwrap_or_default();
        DynamodbSpanBuilder::delete_resource_policy(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::delete_resource_policy);

impl<'a> AwsInstrumentBuilder<'a> for QueryFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        let attributes = [
            self.get_attributes_to_get()
                .as_attribute(semconv::AWS_DYNAMODB_ATTRIBUTES_TO_GET),
            self.get_consistent_read()
                .as_attribute(semconv::AWS_DYNAMODB_CONSISTENT_READ),
            self.get_index_name()
                .as_attribute(semconv::AWS_DYNAMODB_INDEX_NAME),
            self.get_limit().as_attribute(semconv::AWS_DYNAMODB_LIMIT),
            self.get_projection_expression()
                .as_attribute(semconv::AWS_DYNAMODB_PROJECTION),
            self.get_scan_index_forward()
                .as_attribute(semconv::AWS_DYNAMODB_SCAN_FORWARD),
            self.get_select().as_attribute(semconv::AWS_DYNAMODB_SELECT),
        ];
        DynamodbSpanBuilder::query(table_name)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::query);

impl<'a> AwsInstrumentBuilder<'a> for ScanFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        let attributes = [
            self.get_attributes_to_get()
                .as_attribute(semconv::AWS_DYNAMODB_ATTRIBUTES_TO_GET),
            self.get_consistent_read()
                .as_attribute(semconv::AWS_DYNAMODB_CONSISTENT_READ),
            self.get_index_name()
                .as_attribute(semconv::AWS_DYNAMODB_INDEX_NAME),
            self.get_limit().as_attribute(semconv::AWS_DYNAMODB_LIMIT),
            self.get_projection_expression()
                .as_attribute(semconv::AWS_DYNAMODB_PROJECTION),
            self.get_select().as_attribute(semconv::AWS_DYNAMODB_SELECT),
            self.get_segment()
                .as_attribute(semconv::AWS_DYNAMODB_SEGMENT),
            self.get_total_segments()
                .as_attribute(semconv::AWS_DYNAMODB_TOTAL_SEGMENTS),
        ];
        DynamodbSpanBuilder::scan(table_name).attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::scan);

impl<'a> AwsInstrumentBuilder<'a> for BatchGetItemFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_names = self
            .get_request_items()
            .iter()
            .flat_map(|items| items.keys())
            .map(ToOwned::to_owned);
        let attributes = [self
            .get_request_items()
            .as_ref()
            .map(|items| items.len())
            .as_attribute(semconv::DB_OPERATION_BATCH_SIZE)];
        DynamodbSpanBuilder::batch_get_item(table_names)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::batch_get_item);

impl<'a> AwsInstrumentBuilder<'a> for BatchWriteItemFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_names = self
            .get_request_items()
            .iter()
            .flat_map(|items| items.keys())
            .map(ToOwned::to_owned);
        let attributes = [self
            .get_request_items()
            .as_ref()
            .map(|items| items.len())
            .as_attribute(semconv::DB_OPERATION_BATCH_SIZE)];
        DynamodbSpanBuilder::batch_write_item(table_names)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::batch_write_item);

impl<'a> AwsInstrumentBuilder<'a> for TransactGetItemsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_names = self
            .get_transact_items()
            .iter()
            .flatten()
            .flat_map(|item| item.get().map(|op| op.table_name()))
            .collect::<HashSet<_>>()
            .into_iter()
            .map(ToOwned::to_owned);
        DynamodbSpanBuilder::transact_get_items(table_names)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::transact_get_items);

impl<'a> AwsInstrumentBuilder<'a> for TransactWriteItemsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_names = self
            .get_transact_items()
            .iter()
            .flatten()
            .flat_map(|item| {
                [
                    item.condition_check().map(|op| op.table_name()),
                    item.put().map(|op| op.table_name()),
                    item.delete().map(|op| op.table_name()),
                    item.update().map(|op| op.table_name()),
                ]
            })
            .flatten()
            .collect::<HashSet<_>>()
            .into_iter()
            .map(ToOwned::to_owned);
        DynamodbSpanBuilder::transact_write_items(table_names)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::transact_write_items);

// Table management operations
impl<'a> AwsInstrumentBuilder<'a> for CreateTableFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        let throughput = self.get_provisioned_throughput().as_ref();
        let attributes = [
            throughput
                .map(|pt| pt.read_capacity_units())
                .as_attribute(semconv::AWS_DYNAMODB_PROVISIONED_READ_CAPACITY),
            throughput
                .map(|pt| pt.write_capacity_units())
                .as_attribute(semconv::AWS_DYNAMODB_PROVISIONED_WRITE_CAPACITY),
        ];
        DynamodbSpanBuilder::create_table(table_name)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::create_table);

impl<'a> AwsInstrumentBuilder<'a> for DeleteTableFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::delete_table(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::delete_table);

impl<'a> AwsInstrumentBuilder<'a> for DescribeTableFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::describe_table(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::describe_table);

impl<'a> AwsInstrumentBuilder<'a> for UpdateTableFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        let throughput = self.get_provisioned_throughput().as_ref();
        let attributes = [
            throughput
                .map(|pt| pt.read_capacity_units())
                .as_attribute(semconv::AWS_DYNAMODB_PROVISIONED_READ_CAPACITY),
            throughput
                .map(|pt| pt.write_capacity_units())
                .as_attribute(semconv::AWS_DYNAMODB_PROVISIONED_WRITE_CAPACITY),
        ];
        DynamodbSpanBuilder::update_table(table_name)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::update_table);

impl<'a> AwsInstrumentBuilder<'a> for ListTablesFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let attributes = [
            self.get_exclusive_start_table_name()
                .as_attribute(semconv::AWS_DYNAMODB_EXCLUSIVE_START_TABLE),
            self.get_limit().as_attribute(semconv::AWS_DYNAMODB_LIMIT),
        ];
        DynamodbSpanBuilder::list_tables().attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::list_tables);

// Backup operations
impl<'a> AwsInstrumentBuilder<'a> for CreateBackupFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::create_backup(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::create_backup);

impl<'a> AwsInstrumentBuilder<'a> for DeleteBackupFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        DynamodbSpanBuilder::delete_backup()
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::delete_backup);

impl<'a> AwsInstrumentBuilder<'a> for DescribeBackupFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        DynamodbSpanBuilder::describe_backup()
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::describe_backup);

impl<'a> AwsInstrumentBuilder<'a> for ListBackupsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::list_backups(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::list_backups);

impl<'a> AwsInstrumentBuilder<'a> for RestoreTableFromBackupFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let target_table_name = self.get_target_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::restore_table_from_backup(target_table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::restore_table_from_backup);

impl<'a> AwsInstrumentBuilder<'a> for RestoreTableToPointInTimeFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let target_table_name = self.get_target_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::restore_table_to_point_in_time(target_table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::restore_table_to_point_in_time);

// PartiQL operations
impl<'a> AwsInstrumentBuilder<'a> for ExecuteStatementFluentBuilder {
    /// Table names are not automatically extracted from PartiQL statement
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let attributes = [
            self.get_consistent_read()
                .as_attribute(semconv::AWS_DYNAMODB_CONSISTENT_READ),
            self.get_limit().as_attribute(semconv::AWS_DYNAMODB_LIMIT),
        ];
        DynamodbSpanBuilder::execute_statement(None::<StringValue>)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::execute_statement);

impl<'a> AwsInstrumentBuilder<'a> for BatchExecuteStatementFluentBuilder {
    /// Table names are not automatically extracted from PartiQL statement
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        DynamodbSpanBuilder::batch_execute_statement(None::<StringValue>)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::batch_execute_statement);

impl<'a> AwsInstrumentBuilder<'a> for ExecuteTransactionFluentBuilder {
    /// Table names are not automatically extracted from PartiQL statement
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        DynamodbSpanBuilder::execute_transaction(None::<StringValue>)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::execute_transaction);

// Additional global operations
impl<'a> AwsInstrumentBuilder<'a> for DescribeEndpointsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        DynamodbSpanBuilder::describe_endpoints()
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::describe_endpoints);

impl<'a> AwsInstrumentBuilder<'a> for DescribeLimitsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        DynamodbSpanBuilder::describe_limits()
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::describe_limits);

impl<'a> AwsInstrumentBuilder<'a> for ListGlobalTablesFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let attributes = [
            self.get_exclusive_start_global_table_name()
                .as_attribute(semconv::AWS_DYNAMODB_EXCLUSIVE_START_TABLE),
            self.get_limit().as_attribute(semconv::AWS_DYNAMODB_LIMIT),
            self.get_region_name().as_attribute(semconv::CLOUD_REGION),
        ];
        DynamodbSpanBuilder::list_global_tables()
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::list_global_tables);

// Import/Export operations
impl<'a> AwsInstrumentBuilder<'a> for DescribeExportFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        DynamodbSpanBuilder::describe_export()
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::describe_export);

impl<'a> AwsInstrumentBuilder<'a> for DescribeImportFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        DynamodbSpanBuilder::describe_import()
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::describe_import);

impl<'a> AwsInstrumentBuilder<'a> for ImportTableFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self
            .get_table_creation_parameters()
            .as_ref()
            .map(|p| p.table_name())
            .map(ToOwned::to_owned)
            .unwrap_or_default();
        DynamodbSpanBuilder::import_table(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::import_table);

impl<'a> AwsInstrumentBuilder<'a> for ExportTableToPointInTimeFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_arn = self.get_table_arn().clone().unwrap_or_default();
        DynamodbSpanBuilder::export_table_to_point_in_time(table_arn)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::export_table_to_point_in_time);

impl<'a> AwsInstrumentBuilder<'a> for ListExportsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_arn = self.get_table_arn().clone().unwrap_or_default();
        let attributes = [self
            .get_max_results()
            .as_attribute(semconv::AWS_DYNAMODB_LIMIT)];
        DynamodbSpanBuilder::list_exports(table_arn)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::list_exports);

impl<'a> AwsInstrumentBuilder<'a> for ListImportsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_arn = self.get_table_arn().clone().unwrap_or_default();
        let attributes = [self
            .get_page_size()
            .as_attribute(semconv::AWS_DYNAMODB_LIMIT)];
        DynamodbSpanBuilder::list_imports(table_arn)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::list_imports);

// Global table operations
impl<'a> AwsInstrumentBuilder<'a> for CreateGlobalTableFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let global_table_name = self.get_global_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::create_global_table(global_table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::create_global_table);

impl<'a> AwsInstrumentBuilder<'a> for DescribeGlobalTableFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let global_table_name = self.get_global_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::describe_global_table(global_table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::describe_global_table);

impl<'a> AwsInstrumentBuilder<'a> for DescribeGlobalTableSettingsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let global_table_name = self.get_global_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::describe_global_table_settings(global_table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::describe_global_table_settings);

impl<'a> AwsInstrumentBuilder<'a> for UpdateGlobalTableFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let global_table_name = self.get_global_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::update_global_table(global_table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::update_global_table);

impl<'a> AwsInstrumentBuilder<'a> for UpdateGlobalTableSettingsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let global_table_name = self.get_global_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::update_global_table_settings(global_table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::update_global_table_settings);

// Additional table management operations
impl<'a> AwsInstrumentBuilder<'a> for DescribeContinuousBackupsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::describe_continuous_backups(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::describe_continuous_backups);

impl<'a> AwsInstrumentBuilder<'a> for UpdateContinuousBackupsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::update_continuous_backups(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::update_continuous_backups);

impl<'a> AwsInstrumentBuilder<'a> for DescribeTimeToLiveFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::describe_time_to_live(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::describe_time_to_live);

impl<'a> AwsInstrumentBuilder<'a> for UpdateTimeToLiveFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::update_time_to_live(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::update_time_to_live);

impl<'a> AwsInstrumentBuilder<'a> for DescribeTableReplicaAutoScalingFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::describe_table_replica_auto_scaling(table_name)
    }
}
instrument_aws_operation!(
    aws_sdk_dynamodb::operation::describe_table_replica_auto_scaling
);

impl<'a> AwsInstrumentBuilder<'a> for UpdateTableReplicaAutoScalingFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::update_table_replica_auto_scaling(table_name)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::update_table_replica_auto_scaling);

// Kinesis streaming operations
impl<'a> AwsInstrumentBuilder<'a> for DescribeKinesisStreamingDestinationFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::describe_kinesis_streaming_destination(table_name)
    }
}
instrument_aws_operation!(
    aws_sdk_dynamodb::operation::describe_kinesis_streaming_destination
);

impl<'a> AwsInstrumentBuilder<'a> for EnableKinesisStreamingDestinationFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::enable_kinesis_streaming_destination(table_name)
    }
}
instrument_aws_operation!(
    aws_sdk_dynamodb::operation::enable_kinesis_streaming_destination
);

impl<'a> AwsInstrumentBuilder<'a> for DisableKinesisStreamingDestinationFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::disable_kinesis_streaming_destination(table_name)
    }
}
instrument_aws_operation!(
    aws_sdk_dynamodb::operation::disable_kinesis_streaming_destination
);

impl<'a> AwsInstrumentBuilder<'a> for UpdateKinesisStreamingDestinationFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        DynamodbSpanBuilder::update_kinesis_streaming_destination(table_name)
    }
}
instrument_aws_operation!(
    aws_sdk_dynamodb::operation::update_kinesis_streaming_destination
);

// Contributor insights operations
impl<'a> AwsInstrumentBuilder<'a> for DescribeContributorInsightsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        let attributes = [self
            .get_index_name()
            .as_attribute(semconv::AWS_DYNAMODB_INDEX_NAME)];
        DynamodbSpanBuilder::describe_contributor_insights(table_name)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::describe_contributor_insights);

impl<'a> AwsInstrumentBuilder<'a> for ListContributorInsightsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        let attributes = [self
            .get_max_results()
            .as_attribute(semconv::AWS_DYNAMODB_LIMIT)];
        DynamodbSpanBuilder::list_contributor_insights(table_name)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::list_contributor_insights);

impl<'a> AwsInstrumentBuilder<'a> for UpdateContributorInsightsFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let table_name = self.get_table_name().clone().unwrap_or_default();
        let attributes = [self
            .get_index_name()
            .as_attribute(semconv::AWS_DYNAMODB_INDEX_NAME)];
        DynamodbSpanBuilder::update_contributor_insights(table_name)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::update_contributor_insights);

// Resource tagging operations
impl<'a> AwsInstrumentBuilder<'a> for ListTagsOfResourceFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let resource_arn = self.get_resource_arn().clone().unwrap_or_default();
        DynamodbSpanBuilder::list_tags_of_resource(resource_arn)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::list_tags_of_resource);

impl<'a> AwsInstrumentBuilder<'a> for TagResourceFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let resource_arn = self.get_resource_arn().clone().unwrap_or_default();
        DynamodbSpanBuilder::tag_resource(resource_arn)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::tag_resource);

impl<'a> AwsInstrumentBuilder<'a> for UntagResourceFluentBuilder {
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let resource_arn = self.get_resource_arn().clone().unwrap_or_default();
        DynamodbSpanBuilder::untag_resource(resource_arn)
    }
}
instrument_aws_operation!(aws_sdk_dynamodb::operation::untag_resource);
