/// AWS SNS fluent builder instrumentation implementations
/// Generated by GitHub Copilot with human guidance
use super::{AwsInstrumentBuilder, utils::*};
use crate::middleware::aws::*;

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::publish::builders::PublishFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let topic_arn = self.get_target_arn().clone().unwrap_or_default();
        SnsSpanBuilder::publish(topic_arn)
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::publish);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::publish_batch::builders::PublishBatchFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let topic_arn = self.get_topic_arn().clone().unwrap_or_default();
        let attributes = [self
            .get_publish_batch_request_entries()
            .as_ref()
            .map(|entries| entries.len())
            .as_attribute(semconv::MESSAGING_BATCH_MESSAGE_COUNT)];
        SnsSpanBuilder::publish_batch(topic_arn)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::publish_batch);

// Topic management operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::create_topic::builders::CreateTopicFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::create_topic()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::create_topic);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::delete_topic::builders::DeleteTopicFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let topic_arn = self.get_topic_arn().clone().unwrap_or_default();
        SnsSpanBuilder::delete_topic(topic_arn)
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::delete_topic);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::get_topic_attributes::builders::GetTopicAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let topic_arn = self.get_topic_arn().clone().unwrap_or_default();
        SnsSpanBuilder::get_topic_attributes(topic_arn)
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::get_topic_attributes);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::set_topic_attributes::builders::SetTopicAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let topic_arn = self.get_topic_arn().clone().unwrap_or_default();
        SnsSpanBuilder::set_topic_attributes(topic_arn)
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::set_topic_attributes);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::list_topics::builders::ListTopicsFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::list_topics()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::list_topics);

// Subscription operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::subscribe::builders::SubscribeFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let topic_arn = self.get_topic_arn().clone().unwrap_or_default();
        SnsSpanBuilder::subscribe(topic_arn)
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::subscribe);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::unsubscribe::builders::UnsubscribeFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::unsubscribe()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::unsubscribe);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::confirm_subscription::builders::ConfirmSubscriptionFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let topic_arn = self.get_topic_arn().clone().unwrap_or_default();
        SnsSpanBuilder::confirm_subscription(topic_arn)
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::confirm_subscription);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::list_subscriptions::builders::ListSubscriptionsFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::list_subscriptions()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::list_subscriptions);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::list_subscriptions_by_topic::builders::ListSubscriptionsByTopicFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let topic_arn = self.get_topic_arn().clone().unwrap_or_default();
        SnsSpanBuilder::list_subscriptions_by_topic(topic_arn)
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::list_subscriptions_by_topic);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::get_subscription_attributes::builders::GetSubscriptionAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::get_subscription_attributes()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::get_subscription_attributes);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::set_subscription_attributes::builders::SetSubscriptionAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::set_subscription_attributes()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::set_subscription_attributes);

// Permission operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::add_permission::builders::AddPermissionFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let topic_arn = self.get_topic_arn().clone().unwrap_or_default();
        SnsSpanBuilder::add_permission(topic_arn)
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::add_permission);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::remove_permission::builders::RemovePermissionFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let topic_arn = self.get_topic_arn().clone().unwrap_or_default();
        SnsSpanBuilder::remove_permission(topic_arn)
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::remove_permission);

// Platform application operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::create_platform_application::builders::CreatePlatformApplicationFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::create_platform_application()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::create_platform_application);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::delete_platform_application::builders::DeletePlatformApplicationFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::delete_platform_application()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::delete_platform_application);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::get_platform_application_attributes::builders::GetPlatformApplicationAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::get_platform_application_attributes()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::get_platform_application_attributes);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::set_platform_application_attributes::builders::SetPlatformApplicationAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::set_platform_application_attributes()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::set_platform_application_attributes);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::list_platform_applications::builders::ListPlatformApplicationsFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::list_platform_applications()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::list_platform_applications);

// Platform endpoint operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::create_platform_endpoint::builders::CreatePlatformEndpointFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::create_platform_endpoint()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::create_platform_endpoint);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::delete_endpoint::builders::DeleteEndpointFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::delete_endpoint()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::delete_endpoint);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::get_endpoint_attributes::builders::GetEndpointAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::get_endpoint_attributes()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::get_endpoint_attributes);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::set_endpoint_attributes::builders::SetEndpointAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::set_endpoint_attributes()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::set_endpoint_attributes);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::list_endpoints_by_platform_application::builders::ListEndpointsByPlatformApplicationFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::list_endpoints_by_platform_application()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::list_endpoints_by_platform_application);

// Origination number operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::list_origination_numbers::builders::ListOriginationNumbersFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::list_origination_numbers()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::list_origination_numbers);

// Simple phone number operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::check_if_phone_number_is_opted_out::builders::CheckIfPhoneNumberIsOptedOutFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::check_if_phone_number_is_opted_out()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::check_if_phone_number_is_opted_out);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::opt_in_phone_number::builders::OptInPhoneNumberFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::opt_in_phone_number()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::opt_in_phone_number);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::list_phone_numbers_opted_out::builders::ListPhoneNumbersOptedOutFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::list_phone_numbers_opted_out()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::list_phone_numbers_opted_out);

// Add just one SMS operation to test the custom macro
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::get_sms_attributes::builders::GetSMSAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::get_sms_attributes()
    }
}
instrument_aws_operation!(
    aws_sdk_sns::operation::get_sms_attributes,
    GetSMSAttributesFluentBuilder,
    GetSmsAttributesOutput,
    GetSMSAttributesError
);

// SMS sandbox operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::create_sms_sandbox_phone_number::builders::CreateSMSSandboxPhoneNumberFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::create_sms_sandbox_phone_number()
    }
}
instrument_aws_operation!(
    aws_sdk_sns::operation::create_sms_sandbox_phone_number,
    CreateSMSSandboxPhoneNumberFluentBuilder,
    CreateSmsSandboxPhoneNumberOutput,
    CreateSMSSandboxPhoneNumberError
);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::delete_sms_sandbox_phone_number::builders::DeleteSMSSandboxPhoneNumberFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::delete_sms_sandbox_phone_number()
    }
}
instrument_aws_operation!(
    aws_sdk_sns::operation::delete_sms_sandbox_phone_number,
    DeleteSMSSandboxPhoneNumberFluentBuilder,
    DeleteSmsSandboxPhoneNumberOutput,
    DeleteSMSSandboxPhoneNumberError
);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::get_sms_sandbox_account_status::builders::GetSMSSandboxAccountStatusFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::get_sms_sandbox_account_status()
    }
}
instrument_aws_operation!(
    aws_sdk_sns::operation::get_sms_sandbox_account_status,
    GetSMSSandboxAccountStatusFluentBuilder,
    GetSmsSandboxAccountStatusOutput,
    GetSMSSandboxAccountStatusError
);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::list_sms_sandbox_phone_numbers::builders::ListSMSSandboxPhoneNumbersFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::list_sms_sandbox_phone_numbers()
    }
}
instrument_aws_operation!(
    aws_sdk_sns::operation::list_sms_sandbox_phone_numbers,
    ListSMSSandboxPhoneNumbersFluentBuilder,
    ListSmsSandboxPhoneNumbersOutput,
    ListSMSSandboxPhoneNumbersError
);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::verify_sms_sandbox_phone_number::builders::VerifySMSSandboxPhoneNumberFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::verify_sms_sandbox_phone_number()
    }
}
instrument_aws_operation!(
    aws_sdk_sns::operation::verify_sms_sandbox_phone_number,
    VerifySMSSandboxPhoneNumberFluentBuilder,
    VerifySmsSandboxPhoneNumberOutput,
    VerifySMSSandboxPhoneNumberError
);

// SMS attributes operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::set_sms_attributes::builders::SetSMSAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::set_sms_attributes()
    }
}
instrument_aws_operation!(
    aws_sdk_sns::operation::set_sms_attributes,
    SetSMSAttributesFluentBuilder,
    SetSmsAttributesOutput,
    SetSMSAttributesError
);

// Data protection operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::get_data_protection_policy::builders::GetDataProtectionPolicyFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::get_data_protection_policy()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::get_data_protection_policy);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::put_data_protection_policy::builders::PutDataProtectionPolicyFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::put_data_protection_policy()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::put_data_protection_policy);

// Resource tagging operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::list_tags_for_resource::builders::ListTagsForResourceFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::list_tags_for_resource()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::list_tags_for_resource);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::tag_resource::builders::TagResourceFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::tag_resource()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::tag_resource);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sns::operation::untag_resource::builders::UntagResourceFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SnsSpanBuilder::untag_resource()
    }
}
instrument_aws_operation!(aws_sdk_sns::operation::untag_resource);
