/// AWS SQS fluent builder instrumentation implementations
/// Generated by GitHub Copilot with human guidance
use super::{AwsInstrumentBuilder, utils::*};
use crate::{middleware::aws::*, semconv};

// Message operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::send_message::builders::SendMessageFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::send_message(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::send_message);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::send_message_batch::builders::SendMessageBatchFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        let attributes = [self.get_entries()
            .as_ref()
            .map(|entries| entries.len() as i64)
            .as_attribute(semconv::MESSAGING_BATCH_MESSAGE_COUNT)];
        SqsSpanBuilder::send_message_batch(queue_url)
            .attributes(attributes.into_iter().flatten())
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::send_message_batch);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::receive_message::builders::ReceiveMessageFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::receive_message(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::receive_message);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::delete_message::builders::DeleteMessageFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::delete_message(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::delete_message);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::delete_message_batch::builders::DeleteMessageBatchFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::delete_message_batch(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::delete_message_batch);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::change_message_visibility::builders::ChangeMessageVisibilityFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::change_message_visibility(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::change_message_visibility);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::change_message_visibility_batch::builders::ChangeMessageVisibilityBatchFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::change_message_visibility_batch(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::change_message_visibility_batch);

// Queue management operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::create_queue::builders::CreateQueueFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_name = self.get_queue_name().clone().unwrap_or_default();
        SqsSpanBuilder::create_queue(queue_name)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::create_queue);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::delete_queue::builders::DeleteQueueFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::delete_queue(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::delete_queue);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::get_queue_attributes::builders::GetQueueAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::get_queue_attributes(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::get_queue_attributes);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::set_queue_attributes::builders::SetQueueAttributesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::set_queue_attributes(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::set_queue_attributes);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::purge_queue::builders::PurgeQueueFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::purge_queue(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::purge_queue);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::add_permission::builders::AddPermissionFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::add_permission(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::add_permission);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::remove_permission::builders::RemovePermissionFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::remove_permission(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::remove_permission);

// Global operations
impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::get_queue_url::builders::GetQueueUrlFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_name = self.get_queue_name().clone().unwrap_or_default();
        SqsSpanBuilder::get_queue_url(queue_name)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::get_queue_url);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::list_queues::builders::ListQueuesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SqsSpanBuilder::list_queues()
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::list_queues);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::list_queue_tags::builders::ListQueueTagsFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::list_queue_tags(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::list_queue_tags);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::tag_queue::builders::TagQueueFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::tag_queue(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::tag_queue);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::untag_queue::builders::UntagQueueFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::untag_queue(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::untag_queue);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::list_dead_letter_source_queues::builders::ListDeadLetterSourceQueuesFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        let queue_url = self.get_queue_url().clone().unwrap_or_default();
        SqsSpanBuilder::list_dead_letter_source_queues(queue_url)
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::list_dead_letter_source_queues);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::start_message_move_task::builders::StartMessageMoveTaskFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SqsSpanBuilder::start_message_move_task()
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::start_message_move_task);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::cancel_message_move_task::builders::CancelMessageMoveTaskFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SqsSpanBuilder::cancel_message_move_task()
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::cancel_message_move_task);

impl<'a> AwsInstrumentBuilder<'a>
    for aws_sdk_sqs::operation::list_message_move_tasks::builders::ListMessageMoveTasksFluentBuilder
{
    fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
        SqsSpanBuilder::list_message_move_tasks()
    }
}
instrument_aws_operation!(aws_sdk_sqs::operation::list_message_move_tasks);
