/// AWS SSM fluent builder instrumentation implementations
use super::{utils::*, *};

macro_rules! instrument_ssm_operation {
    ($op: ident) => {
        paste::paste! {
            impl<'a> AwsBuilderInstrument<'a> for [<$op:camel FluentBuilder>] {
                fn build_aws_span(&self) -> AwsSpanBuilder<'a> {
                    let attributes = attributes![Some("ssm")
                        .as_attribute("cloud.service.name"),];
                    SsmSpanBuilder::$op().attributes(attributes)
                }
            }

            impl InstrumentedFluentBuilderOutput for [<$op:camel Output>] {}
        }

        instrument_aws_operation!(aws_sdk_ssm::operation::$op);
    };
}

instrument_ssm_operation!(add_tags_to_resource);
instrument_ssm_operation!(associate_ops_item_related_item);
instrument_ssm_operation!(cancel_command);
instrument_ssm_operation!(cancel_maintenance_window_execution);
instrument_ssm_operation!(create_activation);
instrument_ssm_operation!(create_association);
instrument_ssm_operation!(create_association_batch);
instrument_ssm_operation!(create_document);
instrument_ssm_operation!(create_maintenance_window);
instrument_ssm_operation!(create_ops_item);
instrument_ssm_operation!(create_ops_metadata);
instrument_ssm_operation!(create_patch_baseline);
instrument_ssm_operation!(create_resource_data_sync);
instrument_ssm_operation!(delete_activation);
instrument_ssm_operation!(delete_association);
instrument_ssm_operation!(delete_document);
instrument_ssm_operation!(delete_inventory);
instrument_ssm_operation!(delete_maintenance_window);
instrument_ssm_operation!(delete_ops_item);
instrument_ssm_operation!(delete_ops_metadata);
instrument_ssm_operation!(delete_parameter);
instrument_ssm_operation!(delete_parameters);
instrument_ssm_operation!(delete_patch_baseline);
instrument_ssm_operation!(delete_resource_data_sync);
instrument_ssm_operation!(delete_resource_policy);
instrument_ssm_operation!(deregister_managed_instance);
instrument_ssm_operation!(deregister_patch_baseline_for_patch_group);
instrument_ssm_operation!(deregister_target_from_maintenance_window);
instrument_ssm_operation!(deregister_task_from_maintenance_window);
instrument_ssm_operation!(describe_activations);
instrument_ssm_operation!(describe_association);
instrument_ssm_operation!(describe_association_execution_targets);
instrument_ssm_operation!(describe_association_executions);
instrument_ssm_operation!(describe_automation_executions);
instrument_ssm_operation!(describe_automation_step_executions);
instrument_ssm_operation!(describe_available_patches);
instrument_ssm_operation!(describe_document);
instrument_ssm_operation!(describe_document_permission);
instrument_ssm_operation!(describe_effective_instance_associations);
instrument_ssm_operation!(describe_effective_patches_for_patch_baseline);
instrument_ssm_operation!(describe_instance_associations_status);
instrument_ssm_operation!(describe_instance_information);
instrument_ssm_operation!(describe_instance_patch_states);
instrument_ssm_operation!(describe_instance_patch_states_for_patch_group);
instrument_ssm_operation!(describe_instance_patches);
instrument_ssm_operation!(describe_instance_properties);
instrument_ssm_operation!(describe_inventory_deletions);
instrument_ssm_operation!(describe_maintenance_window_execution_task_invocations);
instrument_ssm_operation!(describe_maintenance_window_execution_tasks);
instrument_ssm_operation!(describe_maintenance_window_executions);
instrument_ssm_operation!(describe_maintenance_window_schedule);
instrument_ssm_operation!(describe_maintenance_window_targets);
instrument_ssm_operation!(describe_maintenance_window_tasks);
instrument_ssm_operation!(describe_maintenance_windows);
instrument_ssm_operation!(describe_maintenance_windows_for_target);
instrument_ssm_operation!(describe_ops_items);
instrument_ssm_operation!(describe_parameters);
instrument_ssm_operation!(describe_patch_baselines);
instrument_ssm_operation!(describe_patch_group_state);
instrument_ssm_operation!(describe_patch_groups);
instrument_ssm_operation!(describe_patch_properties);
instrument_ssm_operation!(describe_sessions);
instrument_ssm_operation!(disassociate_ops_item_related_item);
instrument_ssm_operation!(get_access_token);
instrument_ssm_operation!(get_automation_execution);
instrument_ssm_operation!(get_calendar_state);
instrument_ssm_operation!(get_command_invocation);
instrument_ssm_operation!(get_connection_status);
instrument_ssm_operation!(get_default_patch_baseline);
instrument_ssm_operation!(get_deployable_patch_snapshot_for_instance);
instrument_ssm_operation!(get_document);
instrument_ssm_operation!(get_execution_preview);
instrument_ssm_operation!(get_inventory);
instrument_ssm_operation!(get_inventory_schema);
instrument_ssm_operation!(get_maintenance_window);
instrument_ssm_operation!(get_maintenance_window_execution);
instrument_ssm_operation!(get_maintenance_window_execution_task);
instrument_ssm_operation!(get_maintenance_window_execution_task_invocation);
instrument_ssm_operation!(get_maintenance_window_task);
instrument_ssm_operation!(get_ops_item);
instrument_ssm_operation!(get_ops_metadata);
instrument_ssm_operation!(get_ops_summary);
instrument_ssm_operation!(get_parameter);
instrument_ssm_operation!(get_parameter_history);
instrument_ssm_operation!(get_parameters);
instrument_ssm_operation!(get_parameters_by_path);
instrument_ssm_operation!(get_patch_baseline);
instrument_ssm_operation!(get_patch_baseline_for_patch_group);
instrument_ssm_operation!(get_resource_policies);
instrument_ssm_operation!(get_service_setting);
instrument_ssm_operation!(label_parameter_version);
instrument_ssm_operation!(list_association_versions);
instrument_ssm_operation!(list_associations);
instrument_ssm_operation!(list_command_invocations);
instrument_ssm_operation!(list_commands);
instrument_ssm_operation!(list_compliance_items);
instrument_ssm_operation!(list_compliance_summaries);
instrument_ssm_operation!(list_document_metadata_history);
instrument_ssm_operation!(list_document_versions);
instrument_ssm_operation!(list_documents);
instrument_ssm_operation!(list_inventory_entries);
instrument_ssm_operation!(list_nodes);
instrument_ssm_operation!(list_nodes_summary);
instrument_ssm_operation!(list_ops_item_events);
instrument_ssm_operation!(list_ops_item_related_items);
instrument_ssm_operation!(list_ops_metadata);
instrument_ssm_operation!(list_resource_compliance_summaries);
instrument_ssm_operation!(list_resource_data_sync);
instrument_ssm_operation!(list_tags_for_resource);
instrument_ssm_operation!(modify_document_permission);
instrument_ssm_operation!(put_compliance_items);
instrument_ssm_operation!(put_inventory);
instrument_ssm_operation!(put_parameter);
instrument_ssm_operation!(put_resource_policy);
instrument_ssm_operation!(register_default_patch_baseline);
instrument_ssm_operation!(register_patch_baseline_for_patch_group);
instrument_ssm_operation!(register_target_with_maintenance_window);
instrument_ssm_operation!(register_task_with_maintenance_window);
instrument_ssm_operation!(remove_tags_from_resource);
instrument_ssm_operation!(reset_service_setting);
instrument_ssm_operation!(resume_session);
instrument_ssm_operation!(send_automation_signal);
instrument_ssm_operation!(send_command);
instrument_ssm_operation!(start_access_request);
instrument_ssm_operation!(start_associations_once);
instrument_ssm_operation!(start_automation_execution);
instrument_ssm_operation!(start_change_request_execution);
instrument_ssm_operation!(start_execution_preview);
instrument_ssm_operation!(start_session);
instrument_ssm_operation!(stop_automation_execution);
instrument_ssm_operation!(terminate_session);
instrument_ssm_operation!(unlabel_parameter_version);
instrument_ssm_operation!(update_association);
instrument_ssm_operation!(update_association_status);
instrument_ssm_operation!(update_document);
instrument_ssm_operation!(update_document_default_version);
instrument_ssm_operation!(update_document_metadata);
instrument_ssm_operation!(update_maintenance_window);
instrument_ssm_operation!(update_maintenance_window_target);
instrument_ssm_operation!(update_maintenance_window_task);
instrument_ssm_operation!(update_managed_instance_role);
instrument_ssm_operation!(update_ops_item);
instrument_ssm_operation!(update_ops_metadata);
instrument_ssm_operation!(update_patch_baseline);
instrument_ssm_operation!(update_resource_data_sync);
instrument_ssm_operation!(update_service_setting);
