name: "Monthly build"

on:
  schedule:
      - cron: '8 11 8 * *'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu

    env:
      RUSTFLAGS: "-C target-cpu=native"
      RUST_BACKTRACE: full

    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --target ${{ matrix.target }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo test --release --all-features
