name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always
  GITHUB_REPOSITORY: nentgroup/telemetry-rust
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu

    env:
      RUSTFLAGS: "-C target-cpu=native"
      RUST_BACKTRACE: full

    steps:
      - name: Checkout source Git repo
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal --target ${{ matrix.target }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo test --release --all-features
      - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
